from flask import request
from flask_restful import Resource
from price.code import predict_price

class PriceRegressor(Resource):
    # TODO Scheme should be autogenerated somehow?
    def post(self):
        """
        Predicts the price of the real estate property based on its data.

        ---
        parameters:
          - name: body
            in: body
            required: true
            description: Data about the real estate object.
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object
                  description: The data about the property.
                  properties:
                    zipcode:
                      type: integer
                    latitude:
                      type: number
                    longitude:
                      type: number
                    hasCooling:
                      type: integer
                    hasGarage:
                      type: integer
                    hasHeating:
                      type: integer
                    hasView:
                      type: integer
                    parkingSpaces:
                      type: integer
                    yearBuilt:
                      type: integer
                    numOfPhotos:
                      type: integer
                    lotSizeSqFt:
                      type: number
                    livingAreaSqFt:
                      type: number
                    numOfSchools:
                      type: integer
                    numOfBathrooms:
                      type: number
                    numOfBedrooms:
                      type: integer
                    numOfStories:
                      type: integer
        responses:
          200:
            description: The predicted price.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    price:
                      type: number
                      description: The predicted price.
        """
        data: dict = request.get_json()
        if not data:
            return {"error": "Request body cannot be empty."}, 400
        if "data" not in data:
            return {"error": "Request body must contain data"}, 400
        try:
            response = predict_price(data.get("data"))
            return {"price": response}, 200
        except Exception as e:
            return {
                "error": "Price regressor failed.",
                "description": "This is a default description.",
                "details": str(e)
            }, 500


